baseURL = "https://fruworg.github.io/"
anguageCode = "ru-RU"
title = "фрув.орг"
theme = "themu"

pygmentsstyle = "fruity"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
paginate=4 # articles per page

[params]
	mode="dark" # color-mode → light,dark,toggle or auto
	description="всем привет!"
	#useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.

[[menu.main]]
name = "Все посты"
url = "/posts"
weight = 1

[[menu.main]]
name = "Теги"
url = "/tags"
weight = 2
