baseURL = "https://fruw.org/"
anguageCode = "ru-RU"
title = "фрув.орг"
theme = "themu"

pygmentsstyle = "fruity"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
paginate = 4

[params]
description = "всем привет!"
subtitlefile = true
og_image = "fruworg.png"

[[params.social]]
name = "mail"
url = "mailto:im@fruw.org"

[[params.social]]
name = "matrix"
url = "//matrix.to/#/@im:fruw.org"

[[params.social]]
name = "tg"
url = "//t.me/fruworg"

[[params.social]]
name = "pgp"
url = "//keybase.io/fruworg/pgp_keys.asc"

[[params.social]]
name = "keybase"
url = "//keybase.io/fruworg/"

[[params.social]]
name = "up"
url = "//up.fruw.org"

[[params.social]]
name = "git"
url = "//github.com/fruworg"

[[menu.main]]
name = "посты"
url = "/posts"
weight = 1

[[menu.main]]
name = "теги"
url = "/tags"
weight = 2

[[menu.main]]
name = "rss"
url = "/index.xml"
weight = 3
