baseURL = "https://fruw.org/"
languageCode = "ru-RU"
languageName = "Russian"
defaultContentLanguage = 'ru'
title = "fruworg"
theme = "themu"

pygmentsstyle = "fruity"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pagination.pagerSize = 4

[params]
description = "всем привет!"
subtitlefile = true
og_image = "fruworg.jpg"

[[params.social]]
name = "mail"
url = "mailto:im@fruw.org"

[[params.social]]
name = "matrix"
url = "//matrix.to/#/@im:fruw.org"

[[params.social]]
name = "tg"
url = "//t.me/fruworg"

[[params.social]]
name = "pgp"
url = "//keys.openpgp.org/pks/lookup?op=get&options=mr&search=im@fruw.org"

[[params.social]]
name = "id"
url = "//keyoxide.org/86a5f8191783e6f1"

[[params.social]]
name = "up"
url = "//up.fruw.org"

[[params.social]]
name = "git"
url = "//github.com/fruworg"

[[params.social]]
name = "steam"
url = "//steamcommunity.com/id/fruworg"

[[params.social]]
name = "x"
url = "//x.com/fruworg"

[[menu.main]]
name = "посты"
url = "/posts"
weight = 1

[[menu.main]]
name = "теги"
url = "/tags"
weight = 2

[[menu.main]]
name = "rss"
url = "/index.xml"
weight = 3

[[menu.main]]
name = "dn42"
url = "https://dn42.fruw.org"
weight = 4
