baseURL = "https://fruworg.github.io/"
anguageCode = "ru-RU"
title = "фрув.орг"
theme = "themu"

pygmentsstyle = "fruity"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
paginate = 4

[params]
	description = "всем привет!"
	subtitle = "   (@_  добро пожаловать на мой 
\\\_\   open-source веб-сайт!
<____)  12.12.12 12:56 UTC+6"

[[params.social]]
name = "uptime"
url = "https://up.fruw.org"

[[params.social]]
name = "git"
url = "https://github.com/fruworg"

[[params.social]]
name = "mail"
url = "mailto:im@fruw.org"

[[params.social]]
name = "matrix"
url = "https://matrix.to/#/@im:fruw.org"

[[params.social]]
name = "tg"
url = "https://t.me/fruworg"

[[params.social]]
name = "pgp"
url = "https://fruw.org/0x952C15AB751A65F6"

[[menu.main]]
name = "Все посты"
url = "/posts"
weight = 1

[[menu.main]]
name = "Теги"
url = "/tags"
weight = 2
